### ISSUE TITLE
training dataset for  hps classifier is too large to download

### ISSUE THREAD

**Issue by huxian0402** [tgxs002/align_sd#8]
![image](https://github.com/tgxs002/align_sd/assets/37959240/cd807c91-2202-467c-ba74-cbf9e2aff339)
The training dataset for  hps classifier is too large to download. I have tried to download it many times, but all attempts have failed. Would you be able to provide an alternative download link, such as Baidu Cloud or another platform? @tgxs002

**Comment by tgxs002** [comment]
Thank you for reminding... I will host it on Hugging Face, which should be much faster. You can also try using a VPN before that?

**Comment by huxian0402** [comment]
> Thank you for reminding... I will host it on Hugging Face, which should be much faster. You can also try using a VPN before that?

i've tried VPN, but also fail, Hugging Face maybe a better choice.
