### ISSUE TITLE
positive and negative sample data for LoRA training

### ISSUE THREAD

**Issue by huxian0402** [tgxs002/align_sd#9]
![image](https://github.com/tgxs002/align_sd/assets/37959240/3c4830c0-a297-40fe-be88-b14d4b8f6df5)
Hello, I am very interested in your work and I am trying to reproduce your results. Would it be possible for you to share positive and negative sample data you used for LoRA training? @tgxs002

**Comment by tgxs002** [comment]
Sure, but it will also be uploaded to onedrive.

**Comment by tgxs002** [comment]
@huxian0402 Try it out: [link](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155172150_link_cuhk_edu_hk/EZM7Q6DQ3IhLmRNtRytJI2UBxRaH13XwtwQDQrj81AJQwQ?e=kt0ixn).
You may need to subsample half of the negative images to reproduce.
Looking forward to your feedback!

**Comment by huxian0402** [comment]
> @huxian0402 Try it out: [link](https://mycuhk-my.sharepoint.com/:u:/g/personal/1155172150_link_cuhk_edu_hk/EZM7Q6DQ3IhLmRNtRytJI2UBxRaH13XwtwQDQrj81AJQwQ?e=kt0ixn). You may need to subsample half of the negative images to reproduce. Looking forward to your feedback!

Thank you for providing the training data. It was successfully downloaded. However, could you please clarify why this step was necessary? "need to subsample half of the negative images". I see that you used 37k positive samples and 27k negative samples for training. Are you suggesting that sampling should be done according to this ratio for better results?

**Comment by tgxs002** [comment]
No, I used 37k positive samples and 21k negative samples. My experience is that using all negative samples will lead to worse results.
